# Generated by Django 4.1.4 on 2022-12-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_id',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
