# Generated by Django 4.1.4 on 2022-12-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_prodcut'),
    ]

    operations = [
        migrations.CreateModel(
            name='upi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_upi', models.CharField(choices=[('phonepay', 'Phonepay'), ('paytm', 'Paytm')], max_length=50)),
                ('upi_number', models.CharField(max_length=50)),
            ],
        ),
    ]
