# Generated by Django 4.1.4 on 2023-01-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_upi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upi',
            name='select_upi',
            field=models.CharField(choices=[('phonepay', 'Phonepay'), ('paytm', 'Paytm'), ('Gpay', 'Gpay'), ('Tpay', 'Tpay')], max_length=50),
        ),
    ]
