# Generated by Django 4.1.4 on 2023-01-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_alter_upi_select_upi'),
    ]

    operations = [
        migrations.CreateModel(
            name='recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge_amount', models.IntegerField()),
                ('reference_number', models.CharField(max_length=50)),
                ('upi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.upi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.profile')),
            ],
        ),
    ]
