# Generated by Django 4.1.4 on 2023-01-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_kyc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='branck',
            new_name='branch',
        ),
    ]
