# Generated by Django 4.1.4 on 2023-01-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0011_alter_recharge_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.profile'),
        ),
    ]
